/*
**    Generated by Code_Generation toolbox of Xcos with scilab-6.1.0
**    Date : 09-6月-2021
*/

/*---------------------------------------- Actuators */
void TestBlock_actuator(int *flag, int *nport, int *nevprt, double *t, void *u, int *nu1, int *nu2, int *ut, int *flag1)
{
  int k = 0,l = 0;
}
/*---------------------------------------- Sensor */
void TestBlock_sensor(int *flag, int *nport, int *nevprt, double *t, void *y, int *ny1, int *ny2, int *yt, int *flag1)
{
  int k = 0,l = 0;
}
